
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkzjmedpwqskvbqwtujr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFremptZWRwd3Fza3ZicXd0dWpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MTcyNjAsImV4cCI6MjA1OTA5MzI2MH0.iFChdfKR_KIix9V3Ltx6qcj4q8w4P-OvaK-0pTHVFHc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Type definition helper functions
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export type InsertTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert'];
export type UpdateTables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update'];

// Custom type definitions for tables not yet in types.ts
// These will be used until the types.ts file is regenerated with the new tables

// Interface for store_theme_settings table
export interface StoreThemeSettingsRow {
  id: string;
  mode: 'light' | 'dark' | 'system';
  primary_color: string;
  secondary_color: string;
  accent_color: string;
  font_family: string;
  border_radius: string;
  custom_css?: string;
  created_at: string;
  updated_at: string;
}

export interface StoreThemeSettingsInsert {
  id?: string;
  mode?: 'light' | 'dark' | 'system';
  primary_color?: string;
  secondary_color?: string;
  accent_color?: string;
  font_family?: string;
  border_radius?: string;
  custom_css?: string;
  created_at?: string;
  updated_at?: string;
}

// Interface for subscription_plans table
export interface SubscriptionPlanRow {
  id: string;
  name: string;
  price: number;
  description?: string;
  popular?: boolean;
  features: string[];
  not_included: string[];
  created_at: string;
  updated_at: string;
}

export interface SubscriptionPlanInsert {
  id?: string;
  name: string;
  price: number;
  description?: string;
  popular?: boolean;
  features?: string[];
  not_included?: string[];
  created_at?: string;
  updated_at?: string;
}

// Type-safe wrapper functions for standard tables
export const appSettingsTable = () => supabase.from<Tables<'app_settings'>>('app_settings');
export type AppSetting = Tables<'app_settings'>;
export type InsertAppSetting = InsertTables<'app_settings'>;
export type UpdateAppSetting = UpdateTables<'app_settings'>;

// Custom wrapper for subscription_plans table with proper typing
export const subscriptionPlansTable = () => {
  const table = supabase.from('subscription_plans');
  return {
    ...table,
    select: (columns?: string) => table.select(columns),
    insert: (values: SubscriptionPlanInsert | SubscriptionPlanInsert[]) => table.insert(values),
    update: (values: Partial<SubscriptionPlanInsert>) => table.update(values),
    delete: () => table.delete(),
    eq: (column: string, value: any) => table.eq(column, value),
    single: () => table.single(),
    order: (column: string, options?: {ascending?: boolean}) => table.order(column, options),
    limit: (count: number) => table.limit(count),
  };
};
export type SubscriptionPlan = SubscriptionPlanRow;

// Custom wrapper for store_theme_settings table with proper typing
export const storeThemeSettingsTable = () => {
  const table = supabase.from('store_theme_settings');
  return {
    ...table,
    select: (columns?: string) => table.select(columns),
    insert: (values: StoreThemeSettingsInsert | StoreThemeSettingsInsert[]) => table.insert(values),
    update: (values: Partial<StoreThemeSettingsInsert>) => table.update(values),
    delete: () => table.delete(),
    eq: (column: string, value: any) => table.eq(column, value),
    single: () => table.single(),
    order: (column: string, options?: {ascending?: boolean}) => table.order(column, options),
    limit: (count: number) => table.limit(count),
  };
};
export type StoreThemeSetting = StoreThemeSettingsRow;
